-- Tabla de usuarios
CREATE TABLE usuario (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre VARCHAR(100) NOT NULL,
                         email VARCHAR(100) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         rol VARCHAR(20) NOT NULL
);

-- Tabla de mesas
CREATE TABLE mesa (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      numero INTEGER NOT NULL UNIQUE,
                      capacidad INTEGER NOT NULL
);

-- Horarios fijos de turnos
CREATE TABLE turno_horario (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               hora_inicio TIME NOT NULL,
                               hora_fin TIME NOT NULL
);

-- Turnos concretos por día
CREATE TABLE turno_dia (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           fecha DATE NOT NULL,
                           dia_semana VARCHAR(10),
                           turno_horario_id BIGINT NOT NULL,
                           CONSTRAINT fk_turno_dia_horario
                               FOREIGN KEY (turno_horario_id)
                                   REFERENCES turno_horario(id)
);

-- Reservas
CREATE TABLE reserva (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         usuario_id BIGINT NOT NULL,
                         mesa_id BIGINT NOT NULL,
                         turno_dia_id BIGINT NOT NULL,
                         estado VARCHAR(20) NOT NULL,
                         CONSTRAINT fk_reserva_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
                         CONSTRAINT fk_reserva_mesa FOREIGN KEY (mesa_id) REFERENCES mesa(id),
                         CONSTRAINT fk_reserva_turno FOREIGN KEY (turno_dia_id) REFERENCES turno_dia(id),
                         CONSTRAINT uq_reserva_mesa_turno UNIQUE (mesa_id, turno_dia_id)
);

-- Juegos para jugar
CREATE TABLE juego_para_jugar (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nombre VARCHAR(100) NOT NULL,
                                  descripcion TEXT,
                                  cantidad_disponible INTEGER NOT NULL,
                                  imagen_url TEXT,
                                  numero_maximo INTEGER,
                                  dificultad VARCHAR(20),
                                  categoria VARCHAR(100),
                                  duracion_aproximada VARCHAR(50)
);

-- Juegos para vender
CREATE TABLE juego_para_vender (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nombre VARCHAR(100) NOT NULL,
                                   descripcion TEXT,
                                   precio NUMERIC(10,2) NOT NULL,
                                   stock INTEGER NOT NULL,
                                   imagen_url TEXT,
                                   numero_maximo INTEGER,
                                   dificultad VARCHAR(20),
                                   categoria VARCHAR(100),
                                   duracion_aproximada VARCHAR(50)
);