CREATE TABLE evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    fecha DATE NOT NULL,
    descripcion TEXT,
    url TEXT NOT NULL
);

CREATE INDEX idx_evento_fecha ON evento(fecha);
CREATE INDEX idx_evento_titulo ON evento(titulo);
