CREATE TABLE IF NOT EXISTS que_esta_pasando (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS juego_destacado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    cantidad_jugadores VARCHAR(50) NOT NULL,
    duracion VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_que_esta_pasando_fecha_creacion ON que_esta_pasando(fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_que_esta_pasando_titulo ON que_esta_pasando(titulo);
CREATE INDEX IF NOT EXISTS idx_juego_destacado_fecha_creacion ON juego_destacado(fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_juego_destacado_titulo ON juego_destacado(titulo);
